spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fast-rest?useSSL=false&serverTimeZone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: sql839599
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
f:
  ignored-path: /**
  minio:
    endpoint: xxx
    region: fast-rest
    bucket: fast-rest
    access-key: xxx
    secret-key: xxx
server:
  port: 8080
