name: format
on:
  - push
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Code
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: --skip-sorting-imports --replace
          githubToken: ${{secrets.GITHUB_TOKEN}}
          commitMessage: format using google java format
