name: main
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches
          key: ${{runner.os}}-gradle-${{hashFiles('**/build.gradle.kts')}}
          restore-keys: ${{runner.os}}-gradle-
      - name: Build with Gradle
        run: ./gradlew assemble
